// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe13agxRogzhuLZP6L58-sGxrxS4JP7QY',
    appId: '1:247787900477:web:e06a42a101132f0df66454',
    messagingSenderId: '247787900477',
    projectId: 'liquidtech-2339e',
    authDomain: 'liquidtech-2339e.firebaseapp.com',
    storageBucket: 'liquidtech-2339e.appspot.com',
    measurementId: 'G-23CL8H1JWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyUnS7Ko4-igQyg1SlfGt4cNf8Q-8ivSk',
    appId: '1:247787900477:android:4176a8c922699ebcf66454',
    messagingSenderId: '247787900477',
    projectId: 'liquidtech-2339e',
    storageBucket: 'liquidtech-2339e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApSCy7uudKartz9jdh2k2CaZGOu-AW5Zs',
    appId: '1:247787900477:ios:772090ce6267a601f66454',
    messagingSenderId: '247787900477',
    projectId: 'liquidtech-2339e',
    storageBucket: 'liquidtech-2339e.appspot.com',
    iosClientId: '247787900477-191f37lh14ivjbu3b14abaigb1i9t6h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.liquitech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApSCy7uudKartz9jdh2k2CaZGOu-AW5Zs',
    appId: '1:247787900477:ios:772090ce6267a601f66454',
    messagingSenderId: '247787900477',
    projectId: 'liquidtech-2339e',
    storageBucket: 'liquidtech-2339e.appspot.com',
    iosClientId: '247787900477-191f37lh14ivjbu3b14abaigb1i9t6h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.liquitech',
  );
}
